spring:
  application:
    name: Cotato
  profiles:
      active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

weather:
  api-key: d364b0258b887a52cfd560c72aef20ac
  forecast-url: https://api.openweathermap.org/data/2.5/forecast
  current-url: https://api.openweathermap.org/data/2.5/weather
  air-url: https://api.openweathermap.org/data/2.5/air_pollution
  oneCall-Url: https://api.openweathermap.org/data/3.0/onecall
