spring:
  application:
    name: cotato-networking
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# OpenWeather API 설정 추가
openweather:
  api:
    key: ${OPENWEATHER_API_KEY}